# Generated by Django 6.0.7 on 2026-08-24 17:11

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_cases_case_status__3f7d8a_idx_cases_case_status_5f99d2_idx_and_more'),
        ('intake', '0002_consultationrequest'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='consultationrequest',
            name='estimated_budget',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='matter_category',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='practice_area',
        ),
        migrations.RemoveField(
            model_name='consultationrequest',
            name='timeline',
        ),
        migrations.AddField(
            model_name='consultationrequest',
            name='case',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='consultation_requests', to='cases.case'),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='already_have_lawyer',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='best_time_to_consult',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='budget',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='city',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='hearing_scheduled',
            field=models.BooleanField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='preferred_consultation',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AddField(
            model_name='legalissue',
            name='preferred_language',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='consultationrequest',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('WAITING', 'Waiting'), ('ACCEPTED', 'Accepted'), ('ACTIVE', 'Active'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('CANCELLED', 'Cancelled')], default='PENDING', max_length=20),
        ),
    ]
