# Generated by Django 6.0.7 on 2026-09-06 11:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0003_remove_consultationrequest_estimated_budget_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='legalissue',
            name='clarification_data',
            field=models.JSONField(blank=True, default=list),
        ),
    ]
