# Generated by Django 6.0.7 on 2026-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0004_legalissue_clarification_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='assessment_reasoning',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='aianalysis',
            name='preliminary_assessment',
            field=models.CharField(blank=True, max_length=100),
        ),
    ]
