# Generated by Django 6.0.7 on 2026-09-07 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0005_aianalysis_assessment_reasoning_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='aianalysis',
            name='missing_information',
            field=models.JSONField(default=list),
        ),
    ]
