# Generated by Django 6.0.7 on 2026-09-07 18:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('intake', '0006_aianalysis_missing_information'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aianalysis',
            name='cost_estimate',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='important_keywords',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='missing_information',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='possible_acts',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='possible_sections',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='suggested_documents',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='suggested_next_steps',
            field=models.JSONField(blank=True, default=list),
        ),
        migrations.AlterField(
            model_name='aianalysis',
            name='timeline_estimate',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
