# Generated by Django 6.0.7 on 2026-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='profile',
            name='client_type',
            field=models.CharField(blank=True, default='INDIVIDUAL', max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='profile',
            name='organization_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
