# Generated by Django 6.0.7 on 2026-07-30 11:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_profile_client_type_profile_organization_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('ADMIN', 'Administrator'), ('ADVOCATE', 'Advocate'), ('LAW_FIRM', 'Law Firm'), ('CLIENT', 'Client / Citizen')], max_length=20),
        ),
    ]
