# Generated by Django 6.0.7 on 2026-07-30 11:59

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_role'),
        ('cases', '0004_act_casefinancial_caseparty_country_currency_and_more'),
    ]

    operations = [
        migrations.RenameIndex(
            model_name='case',
            new_name='cases_case_status_5f99d2_idx',
            old_name='cases_case_status__3f7d8a_idx',
        ),
        migrations.RemoveField(
            model_name='case',
            name='actual_completion_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='ai_analysed',
        ),
        migrations.RemoveField(
            model_name='case',
            name='bench',
        ),
        migrations.RemoveField(
            model_name='case',
            name='blockchain_verified',
        ),
        migrations.RemoveField(
            model_name='case',
            name='case_type',
        ),
        migrations.RemoveField(
            model_name='case',
            name='category',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_hall',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_level',
        ),
        migrations.RemoveField(
            model_name='case',
            name='court_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='crime_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='currency',
        ),
        migrations.RemoveField(
            model_name='case',
            name='diary_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='diary_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='expected_completion_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='external_reference_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='filing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='fir_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='fir_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='gst_related',
        ),
        migrations.RemoveField(
            model_name='case',
            name='internal_reference_number',
        ),
        migrations.RemoveField(
            model_name='case',
            name='judge',
        ),
        migrations.RemoveField(
            model_name='case',
            name='jurisdiction',
        ),
        migrations.RemoveField(
            model_name='case',
            name='nature_of_case',
        ),
        migrations.RemoveField(
            model_name='case',
            name='next_hearing_date',
        ),
        migrations.RemoveField(
            model_name='case',
            name='opponent_advocate',
        ),
        migrations.RemoveField(
            model_name='case',
            name='pan_related',
        ),
        migrations.RemoveField(
            model_name='case',
            name='police_station',
        ),
        migrations.RemoveField(
            model_name='case',
            name='stage',
        ),
        migrations.RemoveField(
            model_name='case',
            name='tax_related',
        ),
        migrations.RemoveField(
            model_name='case',
            name='visibility',
        ),
        migrations.RemoveField(
            model_name='case',
            name='win_probability',
        ),
        migrations.AddField(
            model_name='case',
            name='ai_analysis_id',
            field=models.UUIDField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_confidence',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='ai_summary',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='case',
            name='assigned_law_firm',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='firm_cases', to='accounts.organization'),
        ),
        migrations.AddField(
            model_name='case',
            name='budget_estimate',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='incident_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='case',
            name='location',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='case',
            name='matter_category',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AddField(
            model_name='case',
            name='matter_source',
            field=models.CharField(choices=[('AI_INTAKE', 'AI Intake'), ('MANUAL', 'Manual Case Creation')], default='MANUAL', max_length=20),
        ),
        migrations.AddField(
            model_name='case',
            name='timeline_estimate',
            field=models.CharField(blank=True, max_length=100),
        ),
        migrations.AlterField(
            model_name='case',
            name='case_number',
            field=models.CharField(db_index=True, max_length=50, unique=True),
        ),
        migrations.AlterField(
            model_name='case',
            name='court',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='case',
            name='priority',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AI_ANALYSED', 'AI Analysed'), ('PENDING_ACCEPTANCE', 'Pending Lawyer Acceptance'), ('LAWYER_ASSIGNED', 'Lawyer Assigned'), ('CONSULTATION', 'Consultation Scheduled'), ('EVIDENCE', 'Evidence Collection'), ('LEGAL_NOTICE', 'Legal Notice'), ('PETITION', 'Petition Drafting'), ('FILED', 'Case Filed'), ('HEARINGS', 'Hearings'), ('JUDGEMENT', 'Judgement Reserved'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived')], default='DRAFT', max_length=50),
        ),
    ]
