# Generated by Django 6.0.7 on 2026-09-05 10:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_cases_case_status__3f7d8a_idx_cases_case_status_5f99d2_idx_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='matter_source',
            field=models.CharField(choices=[('AI_INTAKE', 'AI Intake'), ('TALK_TO_LAWYER', 'Talk to a Lawyer'), ('MANUAL', 'Manual Case Creation')], default='MANUAL', max_length=20),
        ),
    ]
