# Generated by Django 6.0.7 on 2026-09-07 09:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0006_alter_case_matter_source'),
    ]

    operations = [
        migrations.AlterField(
            model_name='case',
            name='status',
            field=models.CharField(choices=[('DRAFT', 'Draft'), ('AI_ANALYSED', 'AI Analysed'), ('PENDING_ACCEPTANCE', 'Pending Lawyer Acceptance'), ('LAWYER_ASSIGNED', 'Lawyer Assigned'), ('CONSULTATION', 'Consultation Scheduled'), ('EVIDENCE', 'Evidence Collection'), ('LEGAL_NOTICE', 'Legal Notice'), ('PETITION', 'Petition Drafting'), ('FILED', 'Case Filed'), ('HEARINGS', 'Hearings'), ('JUDGEMENT', 'Judgement Reserved'), ('CLOSED', 'Closed'), ('ARCHIVED', 'Archived'), ('LAWYER_DECLINED', 'Lawyer Declined')], default='DRAFT', max_length=50),
        ),
    ]
