# Generated by Django 6.0.7 on 2026-07-18 18:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='document',
            name='is_confidential',
            field=models.BooleanField(default=False),
        ),
    ]
