# Generated by Django 6.0.7 on 2026-08-19 19:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0002_document_is_confidential'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='documentversion',
            name='file_size',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.CreateModel(
            name='SignatureRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('DRAFT', 'Draft'), ('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('PARTIALLY_SIGNED', 'Partially Signed'), ('COMPLETED', 'Completed'), ('DECLINED', 'Declined'), ('EXPIRED', 'Expired'), ('CANCELLED', 'Cancelled')], default='DRAFT', max_length=20)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('cancelled_at', models.DateTimeField(blank=True, null=True)),
                ('signing_order_enabled', models.BooleanField(default=False)),
                ('message', models.TextField(blank=True)),
                ('document_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signature_requests', to='documents.documentversion')),
                ('requester', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requested_signatures', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Signer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('email', models.EmailField(blank=True, max_length=254)),
                ('role', models.CharField(blank=True, max_length=100)),
                ('signing_order', models.PositiveIntegerField(default=1)),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VIEWED', 'Viewed'), ('SIGNED', 'Signed'), ('DECLINED', 'Declined')], default='PENDING', max_length=20)),
                ('viewed_at', models.DateTimeField(blank=True, null=True)),
                ('authenticated_at', models.DateTimeField(blank=True, null=True)),
                ('signed_at', models.DateTimeField(blank=True, null=True)),
                ('declined_at', models.DateTimeField(blank=True, null=True)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='signers', to='documents.signaturerequest')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='signature_assignments', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['signing_order', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SignatureField',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('page', models.PositiveIntegerField(default=1)),
                ('x', models.FloatField(default=0.0)),
                ('y', models.FloatField(default=0.0)),
                ('width', models.FloatField(default=100.0)),
                ('height', models.FloatField(default=50.0)),
                ('required', models.BooleanField(default=True)),
                ('field_type', models.CharField(choices=[('SIGNATURE', 'Signature'), ('INITIAL', 'Initial'), ('DATE', 'Date'), ('TEXT', 'Text'), ('CHECKBOX', 'Checkbox')], default='SIGNATURE', max_length=20)),
                ('value', models.TextField(blank=True)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.signaturerequest')),
                ('signer', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='fields', to='documents.signer')),
            ],
        ),
        migrations.CreateModel(
            name='SignatureAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('REQUEST_CREATED', 'Request Created'), ('DOCUMENT_VIEWED', 'Document Viewed'), ('SIGNER_AUTHENTICATED', 'Signer Authenticated'), ('FIELD_COMPLETED', 'Field Completed'), ('SIGNATURE_APPLIED', 'Signature Applied'), ('REQUEST_DECLINED', 'Request Declined'), ('REMINDER_SENT', 'Reminder Sent'), ('REQUEST_CANCELLED', 'Request Cancelled'), ('REQUEST_EXPIRED', 'Request Expired'), ('SIGNING_COMPLETED', 'Signing Completed'), ('SIGNED_DOCUMENT_CREATED', 'Signed Document Created')], max_length=50)),
                ('timestamp', models.DateTimeField(auto_now_add=True)),
                ('ip_address', models.GenericIPAddressField(blank=True, null=True)),
                ('user_agent', models.TextField(blank=True)),
                ('auth_method', models.CharField(blank=True, max_length=100)),
                ('metadata', models.JSONField(blank=True, default=dict)),
                ('event_hash', models.CharField(blank=True, max_length=64)),
                ('previous_event_hash', models.CharField(blank=True, max_length=64)),
                ('actor', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
                ('signature_request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_trail', to='documents.signaturerequest')),
                ('signer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='documents.signer')),
            ],
            options={
                'ordering': ['timestamp', 'id'],
            },
        ),
    ]
