# Generated by Django 6.0.7 on 2026-08-19 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('documents', '0003_documentversion_file_size_signaturerequest_signer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='documentmetadata',
            name='extracted_text',
            field=models.TextField(blank=True, help_text='Text extracted via OCR or native parsing'),
        ),
    ]
