# Generated by Django 6.0.7 on 2026-07-17 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='BlockchainRecord',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('object_id', models.PositiveIntegerField()),
                ('record_type', models.CharField(choices=[('DOCUMENT_HASH', 'Document Hash'), ('CASE_EVENT', 'Case Event'), ('EVIDENCE_CHAIN', 'Evidence Chain of Custody'), ('AUDIT_TRAIL', 'Audit Trail')], max_length=50)),
                ('data_payload', models.JSONField(help_text='The JSON representation of the data that was hashed')),
                ('sha256_hash', models.CharField(help_text='SHA-256 fingerprint of the payload', max_length=64)),
                ('ipfs_cid', models.CharField(blank=True, help_text='IPFS Content Identifier', max_length=100)),
                ('transaction_hash', models.CharField(blank=True, help_text='Ethereum Tx Hash', max_length=100)),
                ('block_number', models.PositiveIntegerField(blank=True, null=True)),
                ('is_verified', models.BooleanField(default=False)),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.contenttype')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('verified_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
                'indexes': [models.Index(fields=['content_type', 'object_id'], name='blockchain__content_0f25c9_idx'), models.Index(fields=['sha256_hash'], name='blockchain__sha256__b77257_idx'), models.Index(fields=['transaction_hash'], name='blockchain__transac_b94fd5_idx')],
            },
        ),
    ]
