# Generated by Django 6.0.7 on 2026-07-17 08:27

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cases', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CasePrediction',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('duration_days_predicted', models.PositiveIntegerField(help_text='Predicted case duration in days')),
                ('success_probability', models.DecimalField(decimal_places=2, help_text='Probability of winning (0-100%)', max_digits=5)),
                ('risk_score', models.DecimalField(decimal_places=2, help_text='Risk score (0-100)', max_digits=5)),
                ('delay_probability', models.DecimalField(decimal_places=2, help_text='Probability of delays (0-100%)', max_digits=5)),
                ('model_version', models.CharField(max_length=50)),
                ('confidence_interval', models.CharField(blank=True, max_length=50)),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='ml_prediction', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CourtWorkload',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('active_cases', models.PositiveIntegerField(default=0)),
                ('pending_cases', models.PositiveIntegerField(default=0)),
                ('average_disposal_time_days', models.PositiveIntegerField(default=0)),
                ('congestion_index', models.DecimalField(decimal_places=2, help_text='0 (Empty) to 100 (Extremely congested)', max_digits=5)),
                ('court', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='workload_stats', to='cases.court')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-congestion_index'],
            },
        ),
    ]
