# Generated by Django 6.0.7 on 2026-08-23 17:47

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_cases_case_status__3f7d8a_idx_cases_case_status_5f99d2_idx_and_more'),
        ('intake', '0002_consultationrequest'),
        ('ml', '0002_featureset_mlmodel_modelversion_modelevaluation_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HistoricalCaseFeature',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('jurisdiction', models.CharField(blank=True, max_length=255)),
                ('court_level', models.CharField(blank=True, max_length=100)),
                ('legal_issues', models.JSONField(blank=True, default=list)),
                ('acts', models.JSONField(blank=True, default=list)),
                ('sections', models.JSONField(blank=True, default=list)),
                ('case_stage', models.CharField(blank=True, max_length=100)),
                ('dispute_type', models.CharField(blank=True, max_length=100)),
                ('relief_sought', models.TextField(blank=True)),
                ('urgency', models.CharField(blank=True, max_length=50)),
                ('complexity', models.CharField(blank=True, max_length=50)),
                ('party_type', models.CharField(blank=True, max_length=100)),
                ('document_types', models.JSONField(blank=True, default=list)),
                ('hearing_count', models.IntegerField(default=0)),
                ('adjournment_count', models.IntegerField(default=0)),
                ('duration_days', models.IntegerField(blank=True, null=True)),
                ('disposition', models.CharField(blank=True, max_length=255)),
                ('outcome_classification', models.CharField(blank=True, max_length=100)),
                ('data_quality_score', models.CharField(choices=[('HIGH', 'High'), ('MEDIUM', 'Medium'), ('LOW', 'Low')], default='LOW', max_length=20)),
                ('semantic_representation', models.TextField(blank=True, help_text='Text representation of the case for embedding')),
                ('embedding', models.JSONField(blank=True, help_text='List of floats representing the dense vector', null=True)),
                ('embedding_model_version', models.CharField(blank=True, max_length=50)),
                ('index_version', models.CharField(blank=True, max_length=50)),
                ('is_synthetic', models.BooleanField(default=False, help_text='True if this is generated demo data')),
                ('case', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='historical_features', to='cases.case')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_historical_case_features',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSearchLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('query_text', models.TextField(blank=True)),
                ('results_count', models.IntegerField(default=0)),
                ('model_version', models.CharField(blank=True, max_length=50)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('trigger_case', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cases.case')),
                ('trigger_issue', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='intake.legalissue')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='historical_searches', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'ml_historical_search_logs',
            },
        ),
        migrations.CreateModel(
            name='HistoricalSearchFeedback',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('feedback_type', models.CharField(choices=[('HIGHLY_RELEVANT', 'Highly Relevant'), ('RELEVANT', 'Relevant'), ('SOMEWHAT_RELEVANT', 'Somewhat Relevant'), ('NOT_RELEVANT', 'Not Relevant'), ('WRONG_CATEGORY', 'Wrong Category')], max_length=50)),
                ('comments', models.TextField(blank=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('deleted_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('retrieved_case', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='retrieval_feedbacks', to='cases.case')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL)),
                ('search_log', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='feedbacks', to='ml.historicalsearchlog')),
            ],
            options={
                'db_table': 'ml_historical_search_feedbacks',
            },
        ),
    ]
