# Generated by Django 6.0.7 on 2026-08-19 18:26

import django.db.models.deletion
import django.utils.timezone
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cases', '0005_rename_cases_case_status__3f7d8a_idx_cases_case_status_5f99d2_idx_and_more'),
        ('hearings', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='HearingAuditLog',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, help_text='Unique identifier', primary_key=True, serialize=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('is_deleted', models.BooleanField(db_index=True, default=False)),
                ('deleted_at', models.DateTimeField(blank=True, null=True)),
                ('is_active', models.BooleanField(db_index=True, default=True)),
                ('action', models.CharField(choices=[('CREATED', 'Created'), ('SCHEDULED', 'Scheduled'), ('RESCHEDULED', 'Rescheduled'), ('ADJOURNED', 'Adjourned'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled'), ('COMPLETED', 'Completed')], max_length=50)),
                ('old_value', models.JSONField(blank=True, null=True)),
                ('new_value', models.JSONField(blank=True, null=True)),
                ('reason', models.TextField(blank=True)),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
        migrations.RemoveIndex(
            model_name='hearing',
            name='hearings_he_case_id_b4d27b_idx',
        ),
        migrations.RemoveIndex(
            model_name='hearing',
            name='hearings_he_presidi_dabedc_idx',
        ),
        migrations.RemoveIndex(
            model_name='hearing',
            name='hearings_he_court_r_a26aa7_idx',
        ),
        migrations.AddField(
            model_name='hearing',
            name='end_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hearing',
            name='mode',
            field=models.CharField(choices=[('PHYSICAL', 'Physical'), ('VIRTUAL', 'Virtual'), ('HYBRID', 'Hybrid')], default='PHYSICAL', max_length=20),
        ),
        migrations.AddField(
            model_name='hearing',
            name='next_action',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='next_hearing_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='notes',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='hearing',
            name='priority',
            field=models.CharField(choices=[('LOW', 'Low'), ('NORMAL', 'Normal'), ('HIGH', 'High'), ('URGENT', 'Urgent')], default='NORMAL', max_length=20),
        ),
        migrations.AddField(
            model_name='hearing',
            name='start_time',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='hearing',
            name='title',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='hearing_type',
            field=models.CharField(choices=[('FIRST_HEARING', 'First Hearing'), ('ADMISSION', 'Admission'), ('ARGUMENTS', 'Arguments'), ('EVIDENCE', 'Evidence'), ('CROSS_EXAMINATION', 'Cross Examination'), ('FINAL_ARGUMENTS', 'Final Arguments'), ('JUDGMENT', 'Judgment'), ('BAIL_HEARING', 'Bail Hearing'), ('INTERIM_APPLICATION', 'Interim Application'), ('MENTIONING', 'Mentioning'), ('MEDIATION', 'Mediation'), ('CONCILIATION', 'Conciliation'), ('OTHER', 'Other')], default='FIRST_HEARING', max_length=50),
        ),
        migrations.AlterField(
            model_name='hearing',
            name='status',
            field=models.CharField(choices=[('SCHEDULED', 'Scheduled'), ('CONFIRMED', 'Confirmed'), ('IN_PROGRESS', 'In Progress'), ('COMPLETED', 'Completed'), ('ADJOURNED', 'Adjourned'), ('POSTPONED', 'Postponed'), ('CANCELLED', 'Cancelled')], default='SCHEDULED', max_length=50),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['case', 'start_time'], name='hearings_he_case_id_0ff6bd_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['presiding_judge', 'start_time'], name='hearings_he_presidi_8403ae_idx'),
        ),
        migrations.AddIndex(
            model_name='hearing',
            index=models.Index(fields=['court_room', 'start_time'], name='hearings_he_court_r_c690f7_idx'),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='actor',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hearing_actions', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='case',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hearing_audit_logs', to='cases.case'),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_created', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='deleted_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='hearing',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='audit_logs', to='hearings.hearing'),
        ),
        migrations.AddField(
            model_name='hearingauditlog',
            name='updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_updated', to=settings.AUTH_USER_MODEL),
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='actual_end_time',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='actual_start_time',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='delay_minutes',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='estimated_duration_minutes',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='scheduled_date',
        ),
        migrations.RemoveField(
            model_name='hearing',
            name='scheduled_time',
        ),
        migrations.AddIndex(
            model_name='hearingauditlog',
            index=models.Index(fields=['hearing', 'created_at'], name='hearings_he_hearing_ad3069_idx'),
        ),
        migrations.AddIndex(
            model_name='hearingauditlog',
            index=models.Index(fields=['case', 'created_at'], name='hearings_he_case_id_4e4a7c_idx'),
        ),
    ]
