# Generated by Django 6.0.7 on 2026-08-19 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notifications', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='notification',
            name='notification_type',
            field=models.CharField(choices=[('SYSTEM', 'System Alert'), ('CASE', 'Case Update'), ('HEARING', 'Hearing Reminder'), ('DOCUMENT', 'Document Upload'), ('AI', 'AI Analysis'), ('BLOCKCHAIN', 'Blockchain Verification'), ('LAWYER_ASSIGNMENT', 'Lawyer Assignment'), ('MESSAGE', 'Message')], default='SYSTEM', max_length=20),
        ),
    ]
